server:
  port: 9090
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: producer-service
          uri: http://localhost:8082/
          predicates: 
            - Path=/producer/**
        - id: consumer-service
          uri: http://localhost:8080/
          predicates:
            - Path=/consumer/**
